wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.9.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.3
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 10
log_interval:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.1
momentum:
  desc: null
  value: 0.1
no_cuda:
  desc: null
  value: false
seed:
  desc: null
  value: 42
test_batch_size:
  desc: null
  value: 10
